config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :urls, only: [:new, :create]
  match '/:uid', to: 'urls#show', via: :get

end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true
  validates :url, :format => URI::regexp(%w(http https))
  validates :user_id, presence: true
  validates :uid, uniqueness: true

  before_save :generate_url_uid

  def generate_url_uid
    begin
      self.uid = SecureRandom.hex(3).first(5)
    end while self.class.exists?(:uid => uid)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :recoverable, :trackable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  validates :first_name, :presence => true, length: { maximum: 50 }, :format => { :with => /\A[a-zA-Z]+\z/, :message => "must contain only letters"}
  validates :last_name, :presence => true, length: { maximum: 50 }, :format => { :with => /\A[a-zA-Z]+\z/, :message => "must contain only letters"}
  has_many :urls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :js, only: [:create]

  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :js, only: [:new, :create]
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @urls ||= current_user.urls.paginate(page: params[:page], :per_page => 5) if user_signed_in?
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate_user!

  def new
    @url = Url.new
  end

  def show
    url = Url.find_by!(uid: params[:uid])
    redirect_to url.url
  end

  def create
    @url = current_user.urls.find_by(url: url_params[:url])
    if @url.nil?
      @url = current_user.urls.build(url_params)
      @url.save
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

    def url_params
      params.require(:url).permit(:url,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_name
    current_user.first_name + ' ' + current_user.last_name if user_signed_in?
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "Numgames Test App | " + yield(:title) : "Numgames Test App" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_url %>">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= link_to 'Create Tiny Url', new_url_path %></li>
            <% else %>
                <li><%= link_to 'Sign In', new_user_session_path  %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <% if user_signed_in? %>
                  <li>Signed in as: <strong><%= user_name  %></strong></li>
                  <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete  %></li>
                  <li><%= link_to 'Create Tiny Url', new_url_path  %></li>
              <% else %>
                  <li><%= link_to 'Sign In', new_user_session_path  %></li>
                  <li><%= link_to 'Sign Up', new_user_registration_path  %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <%= debug(params) if Rails.env.development? %>
        <p>&copy; Company <%= Date.current().year() %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url, remote: true, html: { class: 'form-horizontal'} do |f| %>
  <% if @url.errors.any? %>
      <p class="text-danger">
        <%= pluralize(@url.errors.count, "error") %> prohibited
        this url from being saved:
      <ul class="text-danger">
        <% @url.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
      </p>
  <% end %>
  <%= f.hidden_field :user_id %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :url, {class: 'form-control', placeholder: 'http://google.com'} %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit 'Create', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/urls/_tiny_url.html.erb
<div class="text-default">
  Tiny url <%= link_to root_url + url.uid, url.url, target: '_blank' %> for
  <span class="text-muted"><%= url.url %></span>
</div>

app/views/urls/_url.html.erb
<li>
  <%= render('urls/tiny_url', url: url) %>
</li>

app/views/urls/create.js.erb
<% if @url.errors.empty? %>
    $("#new_url").html("<%= escape_javascript(render('urls/tiny_url', url: @url)) %>");
<% else %>
    $("#new_url").html("<%= escape_javascript(render('urls/form')) %>");
<% end %>

app/views/urls/new.html.erb
<h1>Create a new tiny url</h1>
<div class="well">
    <%= render 'urls/form' %>
</div>